version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nodejs
permissions:
  - object: /home/ubuntu/nodejs/scripts
    pattern: "*"
    owner: ubuntu
    mode: 755
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/remove_before_install.sh
      timeout: 3600
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 3600
  ApplicationStop:
    - location: scripts/stop_server1.sh
      timeout: 3600      
  ApplicationStart:
    - location: scripts/application_start.sh
  #    #runas: root
